@extends('layouts.app')
@section('breadcrumb')
<div class="c-subheader px-3">
    <ol class="breadcrumb border-0 m-0">
        <li class="breadcrumb-item">Human Resources</li>
        <li class="breadcrumb-item"><a href="{{route('payroll.index')}}">Payroll</a></li>
        <li class="breadcrumb-item active">Reports</li>
    </ol>
</div>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Payroll Reports</h5>
                <small class="text-muted">Generate and view payroll reports and analytics</small>
            </div>
            <div class="card-body">
                @if($reports->count() > 0)
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Report Name</th>
                                <th>Type</th>
                                <th>Period</th>
                                <th>Generated Date</th>
                                <th>Generated By</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($reports as $report)
                            <tr>
                                <td>
                                    <strong>{{$report->report_name}}</strong>
                                </td>
                                <td>
                                    <span class="badge badge-{{$report->type_badge}}">{{ucwords(str_replace('_', ' ', $report->report_type))}}</span>
                                </td>
                                <td>
                                    @if($report->payrollPeriod)
                                        {{$report->payrollPeriod->period_name}}
                                    @else
                                        All Periods
                                    @endif
                                </td>
                                <td>{{$report->report_date->format('M d, Y')}}</td>
                                <td>{{$report->generatedBy->name ?? 'System'}}</td>
                                <td>
                                    @if($report->hasFile())
                                        <a href="#" class="btn btn-sm" style="background: linear-gradient(135deg, #6f42c1 0%, #007bff 100%); color: white; border: none; border-radius: 6px; padding: 0.375rem 0.75rem; margin-right: 8px;">
                                            <i class="fas fa-download"></i> Download
                                        </a>
                                    @endif
                                    <span class="text-muted small">{{$report->formatted_size}}</span>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                
                <div class="d-flex justify-content-center">
                    {{$reports->links()}}
                </div>
                @else
                <div class="text-center py-5">
                    <i class="fas fa-chart-bar fa-3x text-muted mb-3"></i>
                    <h5>No Reports Generated</h5>
                    <p class="text-muted">Payroll reports will appear here after processing payroll periods.</p>
                    
                    <div class="mt-4">
                        <h6>Available Report Types:</h6>
                        <div class="row justify-content-center mt-3">
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-md-6 mb-3">
                                        <div class="report-type-card">
                                            <i class="fas fa-file-alt fa-2x text-primary mb-2"></i>
                                            <h6>Payroll Summary</h6>
                                            <small class="text-muted">Complete payroll overview by period</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <div class="report-type-card">
                                            <i class="fas fa-calculator fa-2x text-warning mb-2"></i>
                                            <h6>Tax Report</h6>
                                            <small class="text-muted">Tax deductions and compliance</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <div class="report-type-card">
                                            <i class="fas fa-university fa-2x text-success mb-2"></i>
                                            <h6>Bank Transfer</h6>
                                            <small class="text-muted">Direct deposit file generation</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <div class="report-type-card">
                                            <i class="fas fa-users fa-2x text-info mb-2"></i>
                                            <h6>Employee Summary</h6>
                                            <small class="text-muted">Individual employee reports</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>

<style>
.report-type-card {
    text-align: center;
    padding: 1.5rem;
    border-radius: 8px;
    background: rgba(111, 66, 193, 0.05);
    border: 1px solid rgba(111, 66, 193, 0.1);
    transition: all 0.3s ease;
}

.report-type-card:hover {
    background: rgba(111, 66, 193, 0.1);
    transform: translateY(-2px);
}

.report-type-card h6 {
    color: #333;
    font-weight: 600;
    margin-bottom: 0.5rem;
}
</style>
@endsection
